# -*- coding: utf-8 -*-
"""Transcribeaudio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q8HLTrnNl88XH9vszMMI1CYoOVX3lTGi
"""

#Install Whisper AI:
!pip install git+https://github.com/openai/whisper.git
!sudo apt update && sudo apt install ffmpeg

#Run Whisper AI:
!whisper "/content/drive/MyDrive/Achievements_of_the_Democratic_Party_(Homer_S._Cummings).ogg" --model medium

#Additional arguments:
!whisper -h